title: Your awesome title
 email: your-email@example.com description: >- # this means to ignore newlines until "baseurl:"
  
 baseurl: "" # the subpath of your site, e.g. /blog
 url: "" # the base hostname & protocol for your site, e.g. http://example.com
 twitter_username: jekyllrb
 github_username:  jekyll

 # Build settings
 markdown: rdiscount
 theme: minima
 plugins:
   - jekyll-feed  
webrick:
  headers:
    My-Header: My-Value
My-Other-Header: My-Other-Value

# Personal Recommendation
pygments: true
